### ISSUE TITLE
Bind as UserPrincipalName

### ISSUE THREAD

**Issue by elfwine** [ldapchai/ldapchai#10]
Is there any way to bind the user by providing his userid and domain name?
For example, user@domainname.com

I'm having problem retrieving user's information as the organization unit (OU) varies from user-to-user.

Also, is there any example how to implement changing password and setting the ssl certificate's key?

By the way, this API is very helpful.

Thanks.

**Comment by jrivard** [comment]
It's not documented but ive used user@domain syntax for binding with AD using chai.  It should work just fine.  Chai doesn't do any validation on the username field.  

For dealing with SSL/TLS certificates, your best bet is to write your own TrustManager and set it on the ChaiConfiguration.  There are plenty of examples about on how to create a trust manager.
