### ISSUE TITLE
NmasCrFactory.clearResponseSet does not wipe SAS:Login Secret

### ISSUE THREAD

**Issue by sveldhuisen** [ldapchai/ldapchai#14]
Hi Jason,

long time ago that we worked together on PWM. I hope you are doing fine. I currently have an issue with NmasCrFactory.clearResponseSet (called by SSPR). My testcase is that my SSPR install calls NmasCrFactory.clearResponseSet. NmasCrFactory.clearResponseSet execvutes without any error. However it seems that NmasCrFactory.clearResponseSet whipes 'SAS:Login Secret Key' but not SAS:Login Secret'.

'SAS:Login Secret' actually stores the C/R  so this seems to be a bug. I'm not sure whether this is related to a bug in LDAPchai (i.e. not calling the correct extendedOperation) or NMAS itself.

greetings,

Sebastiaan Veldhuisen

**Comment by jrivard** [comment]
Hi Sabastian.  I don't think this is a PWM/Chai bug.  Chai calls invokes the NMAS API DeleteLoginConfigRequest, which does the clearing.  It's up to the NMAS API to read/write to the SAS* attributes.   Furthermore while I don't think I ever checked the contents of the attributes, the clear command seems to remove the existing response set for all other NMAS API calls, so other then the ascetic issue of some garbage not being removed, im not sure there is any functional impact to your issue?

**Comment by sveldhuisen** [comment]
Hi Jason,

Thanks for your feedback. I'm also working on this issue with MicroFocus technical support. After some further investigation I think you are right: this is not a Chai bug, but rather a NMAS bug. Chai gets a success response back from the NMAS api, but the C/R SAS attributes are not cleared out. The impact is not functional but more technical: the DIB set grows quite fast if you have hundreds of thousands of identities that forget their password and C/R set once in a while.

Kind regards,

--
Sebastiaan Veldhuisen

I D F o c u s   b.v.
Empowering Identity

E:  sveldhuisen@idfocus.nl <mailto:mvreijn@idfocus.nl>
T:  +31 6 1044 3347
W:  www.idfocus.nl <http://www.idfocus.nl/>

Aanwezig: maandag - dinsdag - donderdag - vrijdag

**Comment by sveldhuisen** [comment]
I totally forgot to get back to you on this issue. This bug is identified as an NMAS issue. Thanks for your time.
