### ISSUE TITLE
Where can i find the documentation for implementing CHAI API

### ISSUE THREAD

**Issue by somnath157** [ldapchai/ldapchai#22]
Hi I am new to the AD platform, 
I want to create a self service password reset tool,
I need documentation for how to implement searching of username if it exists and updating a user password
can you help.

**Comment by somnath157** [comment]
How to create a LDAP over SSL connection from my self signed certificate installed in JKS.

**Comment by jrivard** [comment]
Theres a link to the JavaDoc on the github project page.
