### ISSUE TITLE
Support FreeIPA

### ISSUE THREAD

**Issue by edvalley** [ldapchai/ldapchai#26]
FreeIPA uses 389 DS as LDAP backend. I can see two approaches here:
1. Add FreeIPA as a new vendor
2. Extend 389 DS vendor to condition attributes to be read/write

FreeIPA can be detected as root DSE has supported extensions under 2.16.840.1.113730.3.8

@jrivard : What approach do you think will be better?

**Comment by jrivard** [comment]
Added in pull request #27.  Thanks again!
